
project_id = "enqakeujjvnibtcoeewn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
# port = 54324
site_url = "https://amazingpayment.vercel.app"
additional_redirect_urls = ["https://amazingpayment.vercel.app"]
jwt_expiry = 3600
enable_signup = true
# enable_confirmations = true
# enable_email_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = true
# Disable auto-confirmation to require OTP verification
# enable_email_autoconfirm = false

[functions.monitor-crypto-deposits]
verify_jwt = false

[functions.zero-hash-client]
enabled = true
verify_jwt = true
import_map = "./functions/zero-hash-client/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/zero-hash-client/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/zero-hash-client/*.html" ]
