default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8"],
      duration: 1200,
      in_house: false
    )

    build_app(
      scheme: "App",
      workspace: "App.xcworkspace",
      include_bitcode: false
    )

    upload_to_testflight(api_key: api_key)
  end
end
